export const BUTTONS = {
  safe: { label: 'БЕЗОПАСНЫЙ', theme: 'safe', value: 'safe' },
  balanced: { label: 'ОПТИМАЛЬНЫЙ', theme: 'optimal', value: 'balanced' },
  aggressive: { label: 'АГРЕССИВНЫЙ', theme: 'danger', value: 'aggressive' },
  ultra: { label: 'УЛЬТРА', theme: 'lava', value: 'ultra' },
  custom: { label: 'РУЧНЫЕ НАСТРОЙКИ', theme: 'custom', value: 'custom' },
  warning: { label: 'ВНИМАНИЕ', theme: 'warning', value: 'info' },
  tools: { label: 'ИНСТРУМЕНТЫ', theme: 'tools', value: 'tools' },
  V2: { label: 'V2', theme: 'v2', value: 'V2' },
  V3: { label: 'V3', theme: 'v3', value: 'V3' },
  V4: { label: 'V4', theme: 'v4', value: 'V4' },
  gen_2: { label: 'GEN 2', theme: 'gen', value: 'gen_2' },
  gen_3: { label: 'GEN 3', theme: 'gen', value: 'gen_3' },
  mbr: { label: 'MBR', theme: 'partition', value: 'mbr' },
  gpt: { label: 'GPT', theme: 'partition', value: 'gpt' },
  ecc: { label: 'ECC REG', theme: 'server', value: 'ecc' },
  desktop: { label: 'DESKTOP', theme: 'desktop', value: 'desktop' },
  slots1: { label: '1 СЛОТ', theme: 'slots', value: 1 },
  slots2: { label: '2 СЛОТА', theme: 'slots', value: 2 },
  slots3: { label: '3 СЛОТА', theme: 'slots', value: 3 },
  slots4: { label: '4 СЛОТА', theme: 'slots', value: 4 },
  atx: { label: 'ATX', theme: 'board', value: 'atx' },
  matx: { label: 'MATX', theme: 'board', value: 'matx' },
  activate: { label: 'АКТИВИРОВАТЬ', theme: 'danger', value: 'activate' },
  cancel: { label: 'ОТМЕНА', theme: 'safe', value: 'cancel' },
  yes: { label: 'ДА', theme: 'yes', value: 'yes' },
  no: { label: 'НЕТ', theme: 'no', value: 'no' },
} as const;

export type ButtonType = keyof typeof BUTTONS;
